### PR TITLE
Newsfeed bug fixed, closes #126

### LINKED ISSUE #126: Duplicate names in newsfeed
image

### PR DESCRIPTION
**Pull request by imtiyazzaman1**

### CODE REVIEW

File: src/components/Player.js [hunk 1]
```diff
@@ -62,8 +62,6 @@ export class Player extends Component {
           return this.attemptDig(this.props.player.left, this.props.player.top)
         case 73:
           return this.props.handlePopupInventory()
-        case 82:
-          return this.props.handlePopupRPS()
```
Comment (runticle) [inline src/components/Player.js]: and good riddance!
